### ISSUE TITLE
linux sdk not working on ubuntu 16.04

### ISSUE THREAD

**Issue by gierdo** [getsenic/nuimo-linux-python#2]
Hi!

The linux sdk is not working on ubuntu 16.04. 
The test program fails with the following errors:

`
$ sudo PYTHONPATH=./nuimo python examples/test.py
started discovery
Traceback (most recent call last):
  File "examples/test.py", line 92, in <module>
    main()
  File "examples/test.py", line 29, in main
    nuimo_manager.start_discovery()
  File "/home/dominik/workspace_other/nuimo-linux-python/nuimo/nuimo.py", line 324, in start_discovery
    self.nuimos = self.create_nuimos(all_discovered_devices)
  File "/home/dominik/workspace_other/nuimo-linux-python/nuimo/nuimo.py", line 338, in create_nuimos
    return [NuimoController(device) for device in self.filter_nuimos(devices)]
  File "/home/dominik/workspace_other/nuimo-linux-python/nuimo/nuimo.py", line 335, in filter_nuimos
    return [addr for addr, attrs in devices.items() if attrs.get('name') == 'Nuimo']
AttributeError: 'str' object has no attribute 'get'
`

Python is installed from the default sources (2.7.12), the sdk was installed as specified in the Readme with pygattlib from the specified sources.

The issue appears to be this:
[issue 27](https://bitbucket.org/OscarAcena/pygattlib/issues/27/discoveryservice-discover-doesnt-return)

If pygattlib is installed from https://bitbucket.org/OscarAcena/pygattlib everything works fine.
The fix: [diff](https://bitbucket.org/OscarAcena/pygattlib/pull-requests/11/discovering-all-adv-types/diff)

**Comment by larsblumberg** [comment]
Thanks a lot! We'll have a look into it.

**Comment by larsblumberg** [comment]
Fixed with #4 – Nuimo SDK is now using the [original repo](https://bitbucket.org/OscarAcena/pygattlib) as you also suggested. Thanks to @gross1989 for the PR!

**Comment by naimo84** [comment]
For me, it only works, if I install it from here:

`git clone https://github.com/matthewelse/pygattlib`

My install.sh is still (cloned it on September, 8th):

`pygattlib)
        echo "Installing Pygattlib and dependencies"
        set -x
        sudo apt-get install pkg-config libboost-python-dev libboost-thread-dev libbluetooth-dev libglib2.0-dev python-dev
        [ ! -d pygattlib ] && git clone https://github.com/matthewelse/pygattlib
        cd pygattlib && sudo python setup.py install
        ;;
`

I'm developing on a Raspberry Pi 3

**Comment by gross1989** [comment]
The fork of matthewelse has a working discovery method similar to these proposals: [1](https://bitbucket.org/OscarAcena/pygattlib/pull-requests/11/discovering-all-adv-types/diff) and [2](https://bitbucket.org/OscarAcena/pygattlib/issues/27/discoveryservice-discover-doesnt-return#comment-20371154), but it is some commits behind the original and less frequently updated or not maintained any longer.

I suggest to instantiate with the mac address, which works in any case.

**Comment by larsblumberg** [comment]
Hi @gierdo, @naimo84 please try our all new Nuimo Python SDK. It now uses BlueZ's D-Bus API directly. Please find all information here: https://github.com/getsenic/nuimo-linux-python
